version: '3'
networks:
  internal:
    driver: bridge
services:
  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb:1.8
    networks:
      - internal
    ports:
      - 8086:8086
    volumes:
      - /home/azul/docker/influxdb:/var/lib/influxdb
    restart: unless-stopped
  varken:
    hostname: varken
    container_name: varken
    image: boerderij/varken
    networks:
      - internal
    volumes:
      - /home/azul/docker/varken:/config
    environment:
      - TZ=America/New_York
    depends_on:
      - influxdb
    restart: unless-stopped
  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana
    networks:
      - internal
    ports:
      - 3000:3000
    volumes:
      - /home/azul/docker/grafana:/config
    environment:
      - GF_PATHS_DATA=/config/data
      - GF_PATHS_LOGS=/config/logs
      - GF_PATHS_PLUGINS=/config/plugins
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    depends_on:
      - influxdb
      - varken
    restart: unless-stopped
